### ISSUE TITLE
save_dir doesn't work, but dir works?

### ISSUE THREAD

**Issue by datamonsterr** [olimorris/persisted.nvim#10]
I see that you use `save_dir` in the example, and I read your code, you use both `save_dir` and `dir`  but the `save_dir` doesn't work for me and dir works fine. I know that you've just rename `dir` to `save_dir` but seem like there's a bug here?

**Comment by olimorris** [comment]
I changed the api to `save_dir` as it's more explicit but didnt want to break peoples config so left `dir` in. Both should work.
