### ISSUE TITLE
[Bug]: Getting "Could not find a session for" error on any new git repo or branch I open

### ISSUE THREAD

**Issue by miversen33** [olimorris/persisted.nvim#107]
### Your `minimal.lua` config

```lua
local root = "/tmp/persisted"

-- Set stdpaths to use root dir
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- Bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

vim.opt.sessionoptions = "buffers,curdir,folds,globals,tabpages,winpos,winsize" -- Session options to store in the session

-- Install plugins
local plugins = {
  {
    "olimorris/persisted.nvim",
    opts = {
      use_git_branch = true,
      should_autosave = true,
      autoload = true
      -- Your custom config here
    }
  },
  -- Put any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

### Error messages

```vim
[Persisted.nvim]
Could not load a session for branch master
Trying to load a session for branch main ...
[Persisted.nvim]
Could not find a session for /home/miversen/.local/share/nvim/lazy/marks.nvim
As per https://github.com/olimorris/persisted.nvim/discussions/103 you may need to remove the branch from the name
```

### Describe the bug

After the changes referenced in #103 , it seems that autoloading while using git repositories is _kinda_ broken. This issue only pops up when you enter a repository (or branch) for the first time. After the session is created initially it goes away. I ignored the error for a while but it is getting irritating that I am ignoring false errors. Do let me know if there is anything I can provide to help :)

### Reproduce the bug

1) Navigate to a git repository that you have not yet opened (or delete the session for an existing repo)
2) Open neovim in that directory
3) Observe error

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` config file above and still get the issue
- [X] I have used `SessionSave` to save the session before restarting Neovim and using `SessionLoad`
- [X] I have made sure this is not a duplicate issue

**Comment by olimorris** [comment]
Firstly, thanks for the clear issue and the `minmal.lua` config. I'm amazed this is the first time this issue has been raised 😉 . I knew that putting the warning in would cause some clashes but I figured it was a small price to pay to notify users of a breaking change.

I've removed the message now so should fix the issue.

**Comment by miversen33** [comment]
Works for me :) Would you be open to a PR changing your opening print "warnings" to vim.notify?

**Comment by olimorris** [comment]
Oh yes please 😄 !
