### ISSUE TITLE
Handling change in directory before saving

### ISSUE THREAD

**Issue by cnrrobertson** [olimorris/persisted.nvim#32]
Hi, thanks for the amazing plugin!

I have a particular workflow where I will open a session in one directory and then possibly change directory to open files in a separate directory (for example notes in Dropbox). However, once I have done this, my session is automatically saved in the new directory location rather than the original. I'd prefer that once a session is opened, it is always saved back to it's original location.

If this is something you'd be open to implementing, it could use a global variable such as `vim.g.persistlocation` which is used in the `VimLeavePre` autocommand to determine save location rather than the current directory. This could also be a toggleable option.

If it is interesting to you, I'd be happy to submit a PR.

**Comment by cnrrobertson** [comment]
That's right. If I change the working directory (makes telescope searching notes easier), it saves the session file with the new working directory.

And this happens whether I have `curdir` in `sessionoptions` or not..

**Comment by olimorris** [comment]
Got it and completely get the use case.

More than happy to accept a pull request for this and also agree that checking for the presence of a global variable is a neat way to solve this.
