### ISSUE TITLE
[Bug] telescope extension not support width = { val, min, max }

### ISSUE THREAD

**Issue by adoyle-h** [olimorris/persisted.nvim#34]
My default telescope config:

```lua
layout_config = {
  vertical = {
    height = { 0.8, min = 30, max = 80 },
    width = { 0.8, min = 80, max = 130 }
  }
}
```

persisted telescope extension will throw an error.

The extension should use the [`resolver.resolve_width() `](https://github.com/nvim-telescope/telescope.nvim/blob/544c5ee40752ac5552595da86a62abaa39e2dfa9/doc/telescope.txt#L1837-L1853).

**Comment by olimorris** [comment]
Tbh my knowledge with all things Telescope is minimal these days. Happy to accept a PR.
