### ISSUE TITLE
Respect Neovim's `sessionoptions` setting

### ISSUE THREAD

**Issue by CalebDW** [olimorris/persisted.nvim#4]
It would be great if the plugin could respect Neovim's `sessionoptions` setting, instead of having to repeat the list. Another option would be to provide a 'default' flag to pass to the plugin's `options` setting.

Thanks!

**Comment by olimorris** [comment]
Great point! I will look into this, this week!

**Comment by olimorris** [comment]
This should be fixed now, let me know what you think.

I've added in a warning for anyone using a custom options value to let them know to use `vim.o.sessionoptions`.

**Comment by CalebDW** [comment]
It seems to work, thanks for being so responsive about it!
