### ISSUE TITLE
Obsession behavior

### ISSUE THREAD

**Issue by timsofteng** [olimorris/persisted.nvim#42]
Hello. Is it possible to load session which is associated with current folder with `nvim -S` like in obsession?

**Comment by olimorris** [comment]
You can turn `autoload` to true. Not used Obsession in years so can't recall how that works

**Comment by timsofteng** [comment]
> You can turn `autoload` to true. Not used Obsession in years so can't recall how that works

Obsession loads session for current folder with `nvim -S` and with `nvim` it doesn't. Is it possible with persisted.nvim?

**Comment by olimorris** [comment]
> Obsession loads session for current folder with `nvim -S` and with `nvim` it doesn't. Is it possible with persisted.nvim?

No that's not possible. I don't understand your use case and how it differs to using `autoload`
