### ISSUE TITLE
Howto ignore dirs "~" but not "~/*"?

### ISSUE THREAD

**Issue by tmpm697** [olimorris/persisted.nvim#44]
I want to ignore user's home dir specifically but not whatever dirs under that home, so when i at home `cd ~` and start nvim, this session will be ignored.

but when i do like `cd ~/.config/nvim; nvim` then the session for `~/.config/nvim` will `not` be ignored.

howto?

**Comment by latipun7** [comment]
The workaround for now is you could ignore saving session on dashboard or empty buffer.
Example: https://github.com/latipun7/dotfiles/blob/main/home/dot_config/exact_lvim/exact_lua/exact_latipun/exact_plugins/persisted.lua#L20-L24

**Comment by olimorris** [comment]
Yes as @latipun7 correctly refers to in their post, the `should_autosave` callback is the best way to deal with this. You could check for the current workin directory and if it matches `~` then return false.
