### ISSUE TITLE
Error when loading session

### ISSUE THREAD

**Issue by latipun7** [olimorris/persisted.nvim#45]
This plugin error occurred when I tried to load the session. This happened after I updated my neovim and git.

Current neovim (nightly):
```
NVIM v0.9.0-dev-987+g371a74e4e
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```
git version 2.39.2

Error:
```log
E5108: Error executing lua ...site/pack/lazy/opt/persisted.nvim/lua/persisted/init.lua:68: attempt to concatenate field 'branch_separator' (a nil value)
stack traceback:
	...site/pack/lazy/opt/persisted.nvim/lua/persisted/init.lua:68: in function 'get_branch'
	...site/pack/lazy/opt/persisted.nvim/lua/persisted/init.lua:75: in function 'get_current'
	...site/pack/lazy/opt/persisted.nvim/lua/persisted/init.lua:103: in function 'load'
	[string ":lua"]:1: in main chunk
```

**Comment by olimorris** [comment]
Okay thanks for this. Could you share your config too?

**Comment by latipun7** [comment]
This is my config: https://github.com/latipun7/dotfiles/blob/main/home/dot_config/exact_lvim/exact_lua/exact_latipun/exact_plugins/persisted.lua

**Comment by latipun7** [comment]
I'm sorry. Closed this as it turns out the error caused by `lazy.nvim` not loading this plugin on module call. 🙏
