### ISSUE TITLE
Broken functionality

### ISSUE THREAD

**Issue by CalebDW** [olimorris/persisted.nvim#5]
The following features appear to be broken:
- Last session fails to autoload despite `autoload = true`
- No output is generated with `lua require("persisted").list()`

Config:
```
    -- Sessions --
    use {
        "olimorris/persisted.nvim",
        config = function()
            require("persisted").setup({
                use_git_branch = true,
                autoload = true,
                autosave = true,
                allowed_dirs = {"/projects/eaglesys"},
                options = {"curdir", "folds", "help", "tabpages", "winsize", "winpos", "terminal"},
            })
        end
   }
```

Thanks! It's awesome that this plugin supports git branches, I think this is the first one to do so.

Edit: Not sure what happened, but I ran a `PackerSync` again and autoload started working.
Edit #2: Ah, I figured it out. The `allowed_dirs` setting was preventing the autoload (despite me being in that directory). Perhaps I configured it wrong?

**Comment by olimorris** [comment]
Hmmmm weird. Is it working now? I do feel that `allowed_dirs` is not the best name for the variable and may lead to confusion.

Secondly, the `lua require("persisted").list()` does return a table. I won't berate myself too much for this as it is in the readme 😉 . But...I have a custom function which launches a Telescope picker:

```lua
--- functions.lua file
function om.LoadSession()
  local ok, persisted = om.safe_require("persisted")
  if not ok then
    return
  end

  local sessions = persisted.list()
  local path_to_trim = Sessiondir .. "/"

  local sessions_short = {}
  for _, session in pairs(sessions) do
    sessions_short[#sessions_short + 1] = session:gsub(path_to_trim, "")
  end

  om.select("Session to load", sessions_short, function(choice)
    if choice == nil then
      return
    end
    vim.cmd("source " .. vim.fn.fnameescape(path_to_trim .. choice))
    vim.cmd('lua require("persisted").stop()')
  end)
end

--- globals.lua file
function om.select(prompt, choices, callback)
  vim.ui.select(choices, { prompt = prompt }, callback)
end
```

**Comment by CalebDW** [comment]
It is working, but I am not using the `allowed_dirs` option...maybe I should've appended a slash, `/` to the end of the path?

And okay, my apologies---I thought I could create a mapping directly to `lua require("persisted").list()` and have it open in a Telescope window. Perhaps you would consider adding in a telescope extension? Then all that would be required for the user would be something along the lines of (note that I use the cartographer plugin for my mappings):
```
require('telescope').load_extension('persisted')
map.n.nore.silent['<leader>tp'] = ':Telescope persisted<cr>'
```

**Comment by olimorris** [comment]
Love the idea of a telescope extension. I've raised this as a new issue.

Regarding `allowed_dirs`, the plugin compares your current working directory (from Neovim) with the directories listed in the `allowed_dirs` table. I suspect you need the full path. It should work with something like `~/Code/Projects/persisted.nvim`.

**Comment by olimorris** [comment]
I think this is highlighting that I need to do a full readme write up at some point. I tried to stay as close to Folke's as possible but it's starting to fail. Thanks for your great feedback.

**Comment by olimorris** [comment]
> Love the idea of a telescope extension. I've raised this as a new issue.
> 
> Regarding `allowed_dirs`, the plugin compares your current working directory (from Neovim) with the directories listed in the `allowed_dirs` table. I suspect you need the full path. It should work with something like `~/Code/Projects/persisted.nvim`.

@CalebDW I've initially added this via #7 . Let me know what you think. Also updated the readme, heavily!

**Comment by CalebDW** [comment]
> > Love the idea of a telescope extension. I've raised this as a new issue.
> > Regarding `allowed_dirs`, the plugin compares your current working directory (from Neovim) with the directories listed in the `allowed_dirs` table. I suspect you need the full path. It should work with something like `~/Code/Projects/persisted.nvim`.
> 
> @CalebDW I've initially added this via #7 . Let me know what you think. Also updated the readme, heavily!

Awesome! It looks pretty good but I noticed a couple of things:

- There's a missing end-quote:
```
{
  allowed_dirs = {
    "~/Code/Neovim",
    "~/Code/Projects/Ruby"
  }
}
```
- The Telescope window appear to clip the last column. There's also only two columns listed whereas 4 are listed in the README? 
![image](https://user-images.githubusercontent.com/4176520/164109736-e943eff4-ead4-4523-b115-ce5866386a46.png)
- The `allowed_dirs` and `ignored_dirs` needs a little clarification. If a directory is listed, does it include all children as well? For instance, if I want to ignore my home directory ('\~'), would it also prevent autoloading in my projects directory ('~/projects')?

Thanks for the quick turnaround!

**Comment by olimorris** [comment]
Great feedback, thank you! I have pushed updates to the readme and improved the way directories are pattern matched!

Regarding Telescope, can we move that to [this](https://github.com/olimorris/persisted.nvim/issues/7) thread?
