### ISSUE TITLE
Startup time increased dramatically

### ISSUE THREAD

**Issue by abulwafa** [olimorris/persisted.nvim#52]
After the commit 774e4d70e9f0092cc6d2850399fa1ccaca78fc5e

startup time in lazy.nvim increased by 400 msec

**Comment by olimorris** [comment]
That will be the removal of `vim.schedule`. It was only necessary because I'd messed up the autocmds. Just tested myself actually. Wayyyyyyy faster!

**Comment by abulwafa** [comment]
@olimorris unfortunately, using `autoload=true` still causes the same delay.

**Comment by olimorris** [comment]
Are you sure that's not an issue with the plugin you're using to benchmark? My Neovim loads instantly with `autoload = true`:

![Screen Shot 2023-02-27 at 10 37 36](https://user-images.githubusercontent.com/9512444/221541607-b03f694e-268f-47a5-b82c-1a1aff4e3021.gif)

and with `autoload = false`:

<img width="862" alt="Screen Shot 2023-02-27 at 10 38 46@2x" src="https://user-images.githubusercontent.com/9512444/221541801-4a17487a-6c12-419c-9df8-a92689ba7215.png">

<img width="619" alt="Screen Shot 2023-02-27 at 10 39 07@2x" src="https://user-images.githubusercontent.com/9512444/221541853-8d651d3e-4d65-44a1-a19a-f4d45082bafc.png">
