### ISSUE TITLE
[Bug]: Unable to turn off autosaving

### ISSUE THREAD

**Issue by ewok** [olimorris/persisted.nvim#54]
### Your Persisted.nvim config

```lua
{
        save_dir = "sessions/",
        autoload = false,
        autosave = false,
}
```

### What I expect to happen
Not saved session
### What actually happens
Session is saved

I did some small research. I guess it is related to the https://github.com/olimorris/persisted.nvim/blob/main/lua/persisted/init.lua#L148-L153 block.

Small test:

```lua
local function check(conf)
    if (conf.options.autosave and type(conf.options.should_autosave) == "function")
        and not conf.options.should_autosave()
    then
        print("not saving")
    else
        print("saving")
    end
end

-- Works as expected
-- autosave = true and should_autosave = true
local config1 = {}
config1.options = {}
config1.options.autosave = true
config1.options.should_autosave = function()
    return true
end

check(config1)
-- output: saving

-- Doesn't work as expected
-- autosave = false and should_autosave = true
local config2 = {}
config2.options = {}
config2.options.autosave = false
config2.options.should_autosave = function()
    return true
end

check(config2)
-- output: saving

-- Works as expected
-- autosave = true and should_autosave = false
local config3 = {}
config3.options = {}
config3.options.autosave = true
config3.options.should_autosave = function()
    return false
end

check(config3)
-- output: not saving

-- Doesn't work as expected
-- autosave = false and should_autosave = false
local config4 = {}
config4.options = {}
config4.options.autosave = false
config4.options.should_autosave = function()
    return false
end

check(config4)
-- output: saving
```

### Reproduce the bug

Setup minimal.lua with my config.

1 Enter vim.
2. Escape vim.
3. ```ls sessions/ | wc -l```
4. in sessions folder is a saved session.

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` config file above and still get the issue
- [X] I have used `SessionSave` to save the session before restarting Neovim and using `SessionLoad`
- [X] I have made sure this is not a duplicate issue

**Comment by Harsha9554** [comment]
yeah, I'm facing the same issue too. I hope we get a fix I love the plugin so much but I am unable to turn off autosaving. please help if there is a fix.

**Comment by olimorris** [comment]
@ewok thanks for raising this.

To confirm my understanding is correct, you expect:

1. When `autosave = false`, Persisted should _never_ save a session automatically
2. Only when `autosave = true` should the plugin call the `should_autosave` function and based on it boolean output, save the session

**Comment by ewok** [comment]
@olimorris Yes that's right. imho `autosave = false` should completely turn off the autosaving, but it does't. Thank you!

**Comment by ewok** [comment]
@olimorris confirming! Now works like a charm. Thank you so much 👍🏼

**Comment by ewok** [comment]
closing
